name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: run tests
        run: coverage run --branch --source lrbenchmark --module pytest --strict-markers tests/
      - name: report coverage
        run: coverage report
